---
title: "Using `rnoaa` to Acquire Climate Data"
author: "M. Edward (Ed) Borasky"
date: "October 20, 2015"
output: 
  md_document:
    variant: markdown_github
---

## Install the library packages if needed
```{r echo=FALSE}
if (!require(rnoaa)) {
  install.packages('rnoaa')
}
if (!require(dplyr)) {
  install.packages('dplyr')
}
```

## Load the libraries and FIPS code dataset
```{r echo=FALSE}
require(rnoaa)
require(dplyr)
if (file.exists("fipscodes.csv")) {
  fipscodes <- read.csv("fipscodes.csv", stringsAsFactors = FALSE)
} else {
  data(fipscodes)
  fipscodes <- dplyr::filter(fipscodes, state == "Oregon")
  fipscodes <- dplyr::select(fipscodes, -fips_state, -fips_county)

  # save fipscodes as a CSV
  write.csv(fipscodes, file = "fipscodes.csv", row.names = FALSE)
}
```

## Get an API token
1. Go to <http://www.ncdc.noaa.gov/cdo-web/token>.
1. Enter your email address in the form.
1. Press "Submit".
1. Get the API token from your email.
1. Store it in global variable `cdo_token`.

## Make the station table
```{r echo=FALSE}

# define a function to fetch the stations in a single county
dataset <- "NORMAL_MLY" # the "monthly normals" dataset
county_stations <- function(fipscodes, irow) {
  fips <- fipscodes$fips[irow]
  work <- ncdc_stations(
    datasetid = dataset, token = cdo_token, limit = 1000, 
    locationid = paste("FIPS", fips, sep = ":"))
  work <- work$data
  work$fips <- fips
  colnames(work)[10] <- "station_id"
  work <- dplyr::inner_join(fipscodes, work, by = "fips")
  return(work)
}

if (file.exists("station_table.csv")) {
  station_table <- read.csv("station_table.csv", stringsAsFactors = FALSE)
} else {

  # first county
  print(paste("Fetching stations for county =", fipscodes$county[1]))
  station_table <- county_stations(fipscodes, 1)

  # rest of the counties
  for (irow in 2:(nrow(fipscodes))) {
    print(paste("Fetching stations for county =", fipscodes$county[irow]))
    station_table <- dplyr::bind_rows(
      station_table, county_stations(fipscodes, irow))
  }

  # save
  write.csv(station_table, file = "station_table.csv", row.names = FALSE)
}
```

## Make the data table
```{r echo=FALSE}

# function to fetch the data for a single station
start <- "2010-01-01" # required start date parameter
end <- "2010-01-12" # required end date parameter

# data types (variables) to fetch
# "MLY-GRDD-BASE50" is growing degree days with 50 degrees Fahrenheit as the base
# "MLY-PRCP-NORMAL" is precipitation in *hundredths* of an inch
variables <- c("MLY-GRDD-BASE50", "MLY-PRCP-NORMAL")
station_data <- function(station_table, irow) {
  station <- station_table$id[irow]
  work <- ncdc(
    datasetid = dataset, startdate = start, enddate = end,
    token = cdo_token, limit = 1000, stationid = station, datatypeid = variables)
  work <- work$data
  colnames(work)[3] <- "station_id"
  return(work)
}

if (file.exists("data_table.csv")) {
  data_table <- read.csv("data_table.csv", stringsAsFactors = FALSE)
} else {
  
  # first station
  print(paste("Fetching data for station", station_table$id[1]))
  data_table <- station_data(station_table, 1)

  # rest of the counties
  for (irow in 2:(nrow(station_table))) {
    print(paste("Fetching data for station", station_table$id[irow]))
    data_table <- dplyr::bind_rows(data_table, station_data(station_table, irow))
  }
  data_table <- dplyr::inner_join(data_table, station_table, by = "station_id")

  # save
  write.csv(data_table, file = "data_table.csv", row.names = FALSE)
}
```

## Make the result table

```{r echo=FALSE}

# replace -7777 with 0
data_table$value[data_table$value == -7777] <- 0

# summary input table
station_summary <- 
  data_table %>% 
  dplyr::group_by(datatype, county, id) %>% 
  dplyr::summarize(annual_total = sum(value), months = length(value))
write.csv(station_summary, file = "station_summary.csv", row.names = FALSE)
county_summary <-
  station_summary %>% 
  dplyr::group_by(datatype, county) %>% 
  dplyr::summarize(
    county_average = mean(annual_total), stations = length(annual_total))

# round for display
county_summary$value[datatype == "MLY-GRDD-BASE50"] <-
  round(county_summary$value[datatype == "MLY-GRDD-BASE50"], digits = 0)

# convert precipitation to inches
county_summary$value[datatype == "MLY-PRCP-NORMAL"] <-
  round(
    0.01 * county_summary$value[datatype == "MLY-PRCP-NORMAL"], digits = 2)
write.csv(county_summary, file = "county_summary.csv", row.names = FALSE)
```
